# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
# IP: The module: 'dist_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
# IP: The module: 'dist_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
