# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.cache/wt [current_project]
set_property parent.project_path /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/btech/cs1170347/cs1170347_cs1170350_lab6/dhd/simpleAdd.coe
add_files -quiet /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
add_files -quiet /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.dcp
set_property used_in_implementation false [get_files /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.dcp]
read_vhdl -library xil_defaultlib {
  /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/new/debounce.vhd
  /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/new/freq_div_2_14.vhd
  /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/imports/new/CPU_design.vhd
  /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/sources_1/imports/new/memoryInt.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files /home/btech/cs1170347/cs1170347_cs1170350_lab6/cs1170347_cs1170350_lab6.srcs/constrs_1/new/constraint.xdc]


synth_design -top memoryInt -part xc7a35tcpg236-1


write_checkpoint -force -noxdef memoryInt.dcp

catch { report_utilization -file memoryInt_utilization_synth.rpt -pb memoryInt_utilization_synth.pb }
